name: Detect-secrets

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install detect-secrets
        run: |
          python -m pip install --upgrade pip
          python -m pip install detect-secrets==1.0.3
      - name: Find secrets
        run: |
          detect-secrets -v scan --baseline .secrets.baseline
          detect-secrets audit --json --stats > secrets_stats.json
          UNKNOWN_SECRETS_COUNT=$(cat secrets_stats.json | jq .[].stats.raw.unknown)
          REAL_SECRETS_COUNT=$(cat secrets_stats.json | jq .[].stats.raw.\"true-positives\")
          echo $UNKNOWN_SECRETS_COUNT
          echo $UNKNOWN_SECRETS_COUNT
          if [$UNKNOWN_SECRETS_COUNT -gt 0]; then
            echo "Detected new secrets in source code"
            exit 1
          fi
          if [$REAL_SECRETS_COUNT -gt 0]; then
            echo "Detected secrets without fix in source code"
            exit 2
          fi
          
      - name: Remove files
        run: rm -f secrets_stats.json

