name: Detect-secrets analysis

on:
  push:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install detect-secrets
        run: |
          python -m pip install --upgrade pip
          python -m pip install detect-secrets==1.1.0

      - name: Find secrets
        id: secrets
        run: |
          detect-secrets scan --baseline .secrets.baseline
          detect-secrets audit --json --stats .secrets.baseline > secrets_stats.json
          
          cat secrets_stats.json
          
          UNKNOWN_SECRETS_COUNT=$(cat secrets_stats.json | jq .[].stats.raw.unknown | paste -sd+ - | bc -l)
          REAL_SECRETS_COUNT=$(cat secrets_stats.json | jq .[].stats.raw.\"true-positives\" | paste -sd+ - | bc -l)
          
          if [[ $UNKNOWN_SECRETS_COUNT -gt 0 ]]; then
            echo "::error Detected new secrets in source code"
          fi
          if [[ $REAL_SECRETS_COUNT -gt 0 ]]; then
            echo "::warning Detected secrets without fix in source code"
          fi

          echo "::set-output name=unknown-secrets::$UNKNOWN_SECRETS_COUNT"
          echo "::set-output name=real-secrets::$REAL_SECRETS_COUNT"

      - name: Upload baseline
        uses: actions/upload-artifact@v2
        if: ${{ steps.secrets.outputs.unknown-secrets }} > 0
        with:
          name: Secrets references
          path: .secrets.baseline
          if-no-files-found: ignore
          retention-days: 7
          
      - name: Remove files
        run: rm -f secrets_stats.json
      
      - name: Exit
        if: ${{ steps.secrets.outputs.unknown-secrets }} > 0
        run: exit 1

