name: Detect-secrets

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install detect-secrets
        run: |
          python -m pip install --upgrade pip
          pip install detect-secrets==0.14.3
      - name: Run detect-secrets
        run: detect-secrets -v scan . > secrets.json
      - name: Get results
        id: get_results
        run: |
          content=`cat ./secrets.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=baseline::$content"
      - run: |
          echo "${{fromJson(steps.get_results.outputs.baseline).results}}"
          if [[ ${{fromJson(steps.get_results.outputs.baseline).results}} =~ {} ]]
          then
              return 0
          else
              return 1
          fi
