---
name: Flake8 CI
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Flake8 with annotations
        uses: TrueBrain/actions-flake8@v1.4.1
        with:
          # path: src
          max_line_length: 150
