---
name: Yaml Lint
on:
  push:
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: YAML Lint and Annotate
        uses: Staffbase/yamllint-action@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ## The target path is processed recursively
          target-path: .
